// table schema generated by introspection
import { pgTable, uuid, unique, integer, varchar, bigint, timestamp, text } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"

// export const users = pgTable("users", {
// 	id: integer().primaryKey().generatedAlwaysAsIdentity({ name: "users_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 2147483647, cache: 1 }),
// 	name: varchar({ length: 255 }).notNull(),
// 	age: integer().notNull(),
// 	email: varchar({ length: 255 }).notNull(),
// }, (table) => [
// 	unique("users_email_unique").on(table.email)
// ]);

export const sections = pgTable("sections", {
  id: bigint("id", { mode: "number" }).primaryKey(),
  createdAt: timestamp("created_at", {
    withTimezone: true,
    mode: "date",
  }).notNull(),
  title: text("title").notNull(),
  sortOrder: integer("sort_order").notNull(),
});

export const cards = pgTable("cards", {
  id: bigint("id", { mode: "number" })
    .primaryKey()
    .generatedAlwaysAsIdentity(),

  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow().notNull(),

  name: varchar("name", { length: 255 }).notNull(),

  description: text("description"),

  icon: text("icon"),

  link: text("link").notNull(),

  sectionId: bigint("section_id", { mode: "number" }).references(()=>sections.id).notNull(),

  featuredOrder: integer("featured_order"),
});

// 用户profile表
export const profiles = pgTable("profiles", {
  // 与 auth.users.id 保持一致
  id: uuid("id").primaryKey(),

  // 用户昵称
  username: varchar("username", { length: 30 }).notNull().unique(),
  // 头像 URL
  avatar: text("avatar"),
  // 个人简介
  bio: text("bio"),
  // 用户权限
  role: varchar("role", { length: 20 })
    .default("user")
    .notNull(),
  // 当前所属聚落（可为空）
  settlementId: bigint("settlement_id", {
    mode: "number",
  }).references(() => settlements.id),
  // 加入聚落时间
  joinedAt: timestamp("joined_at", {
    withTimezone: true,
  }),

  // 注册时间
  createdAt: timestamp("created_at", {
    withTimezone: true,
  })
    .defaultNow()
    .notNull(),
  // 最后更新时间
  updatedAt: timestamp("updated_at", {
    withTimezone: true,
  })
    .defaultNow()
    .notNull(),
});

// 聚落Card拓展表
export const settlements = pgTable("settlements", {
  // 聚落ID
  id: bigint("id", { mode: "number" })
    .primaryKey()
    .generatedAlwaysAsIdentity(),

  // 对应的 Card
  cardId: bigint("card_id", { mode: "number" })
    .notNull()
    .unique()
    .references(() => cards.id),

  // 创建者（profiles.id）
  creatorId: uuid("creator_id")
  .notNull(),

  // 聚落横幅图片
  banner: text("banner"),
  // 聚落规则
  rules: text("rules"),

  createdAt: timestamp("created_at", {
    withTimezone: true,
  })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", {
    withTimezone: true,
  })
    .defaultNow()
    .notNull(),
});