// table schema generated by introspection
import { pgTable, unique, integer, varchar, bigint, timestamp, text } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"

// export const users = pgTable("users", {
// 	id: integer().primaryKey().generatedAlwaysAsIdentity({ name: "users_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 2147483647, cache: 1 }),
// 	name: varchar({ length: 255 }).notNull(),
// 	age: integer().notNull(),
// 	email: varchar({ length: 255 }).notNull(),
// }, (table) => [
// 	unique("users_email_unique").on(table.email)
// ]);

export const sections = pgTable("sections", {
  id: bigint("id", { mode: "number" }).primaryKey(),
  createdAt: timestamp("created_at", {
    withTimezone: true,
    mode: "date",
  }).notNull(),
  title: text("title").notNull(),
  sortOrder: integer("sort_order").notNull(),
});

export const cards = pgTable("cards", {
  id: bigint("id", { mode: "number" })
    .primaryKey()
    .generatedAlwaysAsIdentity(),

  created_at: timestamp("created_at", { withTimezone: true })
    .defaultNow(),

  name: varchar("name", { length: 255 }).notNull(),

  description: text("description"),

  icon: text("icon"),

  link: text("link").notNull(),

  section_id: bigint("section_id", { mode: "number" }).notNull(),

  featured_order: integer("featured_order"),
});